# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookingcourse',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cookingcourse',
            name='start_date',
            field=models.DateField(),
        ),
    ]
